var _ = require('lodash');
var express = require('express');
var router = express.Router();
var Candidato = require('../model/Candidato.js')
var async = require('async');


var filter = {

  options : {
    ocupacao : {
    "0" : "Presidente da República",
    "1" : "Empresário",
    "2" : "Médico",
    "3" : "Jornalista e Redator",
    "5" : "Senador",
    "6" : "Administrador",
    "7" : "Professor de Ensino Superior",
    "8" : "Professor de Ensino Médio",
    "9" : "Militar Reformado",
    "10" : "Servidor Público Federal",
    "11" : "Advogado",
    "12" : "Historiador",
    "13" : "Deputado",
    "14" : "Bancário e Economiário",
    "15" : "Economista",
    "16" : "Trabalhador Metalúrgico e Siderúrgico",
    "17" : "Cozinheiro",
    "18" : "Outros",
    "19" : "Técnico de Enfermagem e Assemelhados (Exceto Enfermeiro)",
    "20" : "Policial Militar",
    "21" : "Corretor de Imóveis, Seguros, Títulos e Valores",
    "22" : "Locutor e Comentarista de Rádio e Televisão e Radialista",
    "23" : "Servidor Público Estadual",
    "24" : "Agrônomo",
    "25" : "Vigilante",
    "26" : "Enfermeiro",
    "27" : "Professor e Instrutor de Formação Profissional",
    "28" : "Bombeiro Militar",
    "29" : "Professor de Ensino Fundamental",
    "30" : "Estudante, Bolsista, Estagiário e Assemelhados",
    "31" : "Assistente Social",
    "32" : "Vereador",
    "33" : "Membro do Ministério Público",
    "34" : "Governador",
    "35" : "Agricultor",
    "36" : "Gerente",
    "37" : "Dona de Casa",
    "38" : "Comerciante",
    "39" : "Produtor Agropecuário",
    "40" : "Almoxarife",
    "41" : "Aposentado (Exceto Servidor Público)",
    "42" : "Biólogo",
    "43" : "Trabalhador de Construção Civil",
    "44" : "Cantor e Compositor",
    "45" : "Secretário e Datilógrafo",
    "46" : "Pecuarista",
    "47" : "Técnico em Edificações",
    "48" : "Servidor Público Municipal",
    "49" : "Geógrafo",
    "50" : "Fiscal",
    "51" : "Motoboy",
    "52" : "Vendedor de Comércio Varejista e Atacadista",
    "53" : "Contador",
    "54" : "Policial Civil",
    "55" : "Engenheiro",
    "56" : "Cabeleireiro e Barbeiro",
    "57" : "Mecânico de Manutenção",
    "58" : "Agente Administrativo",
    "59" : "Técnico em Agronomia e Agrimensura",
    "60" : "Odontólogo",
    "61" : "Técnico de Obras Civis, Estradas, Saneamento e Assemelhados",
    "62" : "Gari ou Lixeiro",
    "63" : "Fisioterapeuta e Terapeuta Ocupacional",
    "64" : "Técnico de Laboratório e Raios X",
    "65" : "Eletricista e Assemelhados",
    "66" : "Motorista de Veículos de Transporte de Carga",
    "67" : "Auxiliar de Escritório e Assemelhados",
    "68" : "Trabalhador Rural",
    "69" : "Representante Comercial",
    "70" : "Agente de Saúde e Sanitarista",
    "71" : "Faxineiro",
    "72" : "Ministro de Estado",
    "73" : "Vendedor Pracista, Representante, Caixeiro-Viajante e Assemelhados",
    "74" : "Sacerdote ou Membro de Ordem ou Seita Religiosa",
    "75" : "Servidor Público Civil Aposentado",
    "76" : "Técnico de Química",
    "77" : "Astrônomo",
    "78" : "Frentista",
    "79" : "Psicólogo",
    "80" : "Taxista",
    "81" : "Relojoeiro e Montador de Instrumento de Precisão",
    "82" : "Comunicólogo",
    "83" : "Técnico Contabilidade, Estatística, Economia Doméstica e Administração",
    "84" : "Alfaiate e Costureiro",
    "85" : "Motorista de Veículos de Transporte Coletivo de Passageiros",
    "86" : "Músico",
    "87" : "Ator e Diretor de Espetáculos Públicos",
    "88" : "Comerciário",
    "89" : "Garçom",
    "90" : "Analista de Sistemas",
    "91" : "Porteiro de Edifício, Ascensorista, Garagista e Zelador",
    "92" : "Arquiteto",
    "93" : "Farmacêutico",
    "94" : "Guia de Turismo",
    "95" : "Pedagogo",
    "96" : "Recepcionista",
    "97" : "Atleta Profissional e Técnico em Desportos",
    "98" : "Artesão",
    "99" : "Motorista Particular",
    "100" : "Industrial",
    "101" : "Ocupante de Cargo em Comissão",
    "102" : "Diretor de Empresas",
    "103" : "Agente Postal",
    "104" : "Padeiro, Confeiteiro e Assemelhados",
    "105" : "Cobrador de Transporte Coletivo",
    "106" : "Publicitário",
    "107" : "Jornaleiro",
    "108" : "Supervisor, Inspetor e Agente de Compras e Vendas",
    "109" : "Nutricionista e Assemelhados",
    "110" : "Office-Boy e Contínuo",
    "111" : "Diretor de Estabelecimento de Ensino",
    "112" : "Sociólogo",
    "113" : "Fotógrafo e Assemelhados",
    "114" : "Empregado Doméstico",
    "115" : "Técnico em Informática",
    "116" : "Geólogo",
    "117" : "Membro das Forças Armadas",
    "118" : "Serventuário de Justiça",
    "119" : "Veterinário",
    "120" : "Estivador, Carregador e Assemelhados",
    "121" : "Esteticista",
    "122" : "Economista Doméstico",
    "123" : "Químico",
    "124" : "Ceramista e Oleiro",
    "125" : "Decorador",
    "126" : "Técnico de Mecânica",
    "127" : "Carpinteiro, Marceneiro e Assemelhados",
    "128" : "Desenhista",
    "129" : "Relações-Públicas",
    "130" : "Operador de Equipamento de Rádio, Televisão, Som e Cinema",
    "131" : "Artista de Circo",
    "132" : "Operador de Aparelhos de Produção Industrial",
    "133" : "Agente de Viagem",
    "134" : "Massagista",
    "135" : "Embalador, Empacotador e Assemelhados",
    "136" : "Biomédico",
    "137" : "Estofador",
    "138" : "Petroleiro",
    "139" : "Artista Plástico e Assemelhados",
    "140" : "Pescador",
    "141" : "Cientista Político",
    "142" : "Telefonista",
    "143" : "Terapeuta",
    "144" : "Técnico de Eletricidade, Eletrônica e Telecomunicações",
    "145" : "Protético",
    "146" : "Atendente de Lanchonete e Restaurante",
    "147" : "Produtor de Espetáculos Públicos",
    "148" : "Trabalhador de Fabricação de Roupas",
    "149" : "Catador de Recicláveis",
    "150" : "Estatístico",
    "151" : "Diplomata",
    "152" : "Trabalhador Dos Serviços de Contabilidade, de Caixa e Assemelhados",
    "153" : "Feirante, Ambulante e Mascate",
    "154" : "Chaveiro",
    "155" : "Detetive Particular",
    "156" : "Fonoaudiólogo",
    "157" : "Securitário",
    "158" : "Bombeiro Civil",
    "159" : "Serralheiro",
    "160" : "Tradutor, Intérprete e Filólogo",
    "161" : "Fiscal de Transporte Coletivo",
    "162" : "Montador de Estrutura Metálica",
    "163" : "Trabalhador de Minas e Pedreiras, Sondador e Assemelhados",
    "164" : "Trabalhador em Atividade de Processamento Químico",
    "165" : "Coveiro",
    "166" : "Encanador, Soldador, Chapeador e Caldeireiro",
    "167" : "Despachante",
    "168" : "Matemático e Atuário",
    "169" : "Escritor e Crítico",
    "170" : "Zootecnista",
    "171" : "Oceanógrafo",
    "172" : "Funileiro",
    "173" : "Manicure e Maquilador",
    "174" : "Jardineiro",
    "175" : "Trabalhador de Artes Gráficas",
    "176" : "Operador de Instalação de Produção de Energia Elétrica e Nuclear",
    "177" : "Tabelião",
    "178" : "Lanterneiro e Pintor de Veículos",
    "179" : "Bombeiro e Instalador de Gás, Água, Esgoto e Assemelhados",
    "180" : "Auxiliar de Laboratório",
    "181" : "Programador de Computador",
    "182" : "Joalheiro e Ourives",
    "183" : "Digitador",
    "184" : "Torneiro Mecânico",
    "185" : "Bibliotecário",
    "186" : "Piloto de Aviação Comercial, Navegador, Mecânico de Vôo e Assemelhados",
    "187" : "Meteorologista",
    "188" : "Técnico de Biologia",
    "189" : "Marinheiro Civil, Canoeiro, Embarcado e Assemelhados",
    "190" : "Leiturista",
    "191" : "Astrólogo",
    "192" : "Ferroviário",
    "193" : "Trabalhador de Hotelaria",
    "194" : "Geofísico",
    "195" : "Agente de Serviços Funerários e Embalsamador",
    "196" : "Modelo",
    "197" : "Guardador de Veículos",
    "198" : "Trabalhador de Usinagem de Metais",
    "199" : "Prefeito",
    "200" : "Fiandeiro, Tecelão, Tingidor e Assemelhados",
    "201" : "Agenciador de Propaganda",
    "202" : "Trabalhador Florestal",
    "203" : "Comandante de Embarcações",
    "204" : "Operador de Implemento de Agricultura, Pecuária e Exploração Florestal",
    "205" : "Antropólogo",
    "206" : "Operador de Computador",
    "207" : "Técnico de Mineração, Metalurgia e Geologia",
    "208" : "Capitalista de Ativos Financeiros",
    "209" : "Bacteriologista e Assemelhados",
    "210" : "Montador de Máquinas",
    "211" : "Tapeceiro",
    "212" : "Técnico Têxtil",
    "213" : "Trabalhador de Fabricação de Calçados e Artefatos de Couro",
    "214" : "Engraxate"
},
    estado_civil : {
      "0" : "Divorciado(a)",
      "1" : "Casado(a)",
      "2" : "Solteiro(a)",
      "3" : "Separado(a) judicialmente",
      "4" : "Viúvo(a)"
    },
    sexo : {
      "0" : "FEMININO",
      "1" : "MASCULINO"
    },
    grau_instrucao : {
      "0" : "Superior completo",
      "1" : "Superior incompleto",
      "2" : "Ensino Médio completo",
      "3" : "Ensino Médio incompleto",
      "4" : "Ensino Fundamental incompleto",
      "5" : "Ensino Fundamental completo",
      "6" : "Lê e escreve"
    },
    partido : {
      "0" : "Partido dos Trabalhadores",
      "1" : "Partido Social Cristão",
      "2" : "Partido Verde",
      "3" : "Partido Renovador Trabalhista Brasileiro",
      "4" : "",
      "5" : "Partido da Social Democracia Brasileira",
      "6" : "Partido Social Democrata Cristão",
      "7" : "Partido Socialismo e Liberdade",
      "8" : "Partido Socialista dos Trabalhadores Unificado",
      "9" : "Partido do Movimento Democrático Brasileiro",
      "10" : "Partido Comunista Brasileiro",
      "11" : "Partido Socialista Brasileiro",
      "12" : "Partido da Causa Operária",
      "13" : "Partido Republicano Brasileiro",
      "14" : "Partido Progressista",
      "15" : "Partido Popular Socialista",
      "16" : "Partido Humanista da Solidariedade",
      "17" : "Partido Trabalhista do Brasil",
      "18" : "Democratas",
      "19" : "Partido da República",
      "20" : "Partido Social Democrático",
      "21" : "Partido Democrático Trabalhista",
      "22" : "Partido Trabalhista Nacional",
      "23" : "Partido Pátria Livre",
      "24" : "Solidariedade",
      "25" : "Partido Social Liberal",
      "26" : "Partido Comunista do Brasil",
      "27" : "Partido Trabalhista Brasileiro",
      "28" : "Partido Republicano da Ordem Social",
      "29" : "Partido Republicano Progressista",
      "30" : "Partido da Mobilização Nacional",
      "31" : "Partido Ecológico Nacional",
      "32" : "Partido Trabalhista Cristão"
    },
    coligacao : {
    "0" : "PT / PMDB / PSD / PP / PR / PROS / PDT / PC do B / PRB",
    "2" : "PSDB / PMN / SD / DEM / PEN / PTN / PTB / PTC / PT do B",
    "3" : "PHS / PRP / PPS / PPL / PSB / PSL",
    "4" : "PT / PEN / PROS / PDT / PTB / PSL / PTN / PSDC / PHS / PSB / PRP / PPL / PRB / PC do B",
    "5" : "PP / PMDB / PSC / PR / PPS / PTC / PSDB / PSD / PT do B / SD",
    "6" : "DEM / PV / PMN",
    "7" : "PDT / PRB / PT / PSL / PTN / PSDC / PHS / PSB / PRP / PEN / PPL / PC do B / PROS / PTB",
    "8" : "PMDB / PSDB / PT do B / PSC / PTC / PPS / PR / SD / PP / PSD",
    "9" : "PRB / PTN / PHS / PPL",
    "10" : "PMDB / PSDB / PT do B / PTC / PSC",
    "11" : "PSDC / PSL",
    "12" : "PPS / PR / SD",
    "13" : "PT / PEN / PROS",
    "14" : "PC do B / PTB",
    "15" : "PV / PT do B / PMDB / PROS / PC do B / PSC / PHS / PTB / PSD / PDT / PT",
    "16" : "PSDB / PRB",
    "17" : "PSOL / PSTU",
    "18" : "PRTB / PPL / PMN",
    "19" : "PPS / PP / PSDC / PRP / PR / PSL / PSB / DEM / SD",
    "20" : "PROS / PT do B / PHS / PC do B / PV",
    "21" : "PDT / PMDB / PSC / PTB / PSD",
    "22" : "PP / PPS / PSDC / PRP / PR / PSL / PSB / SD / DEM",
    "23" : "PDT / PSC / PMDB / PV / PTB / PSD / PT do B / PROS / PC do B / PT / PHS",
    "24" : "PT do B / PRB / PROS / PR / PEN / PV / PHS / PSDC / PTN",
    "25" : "DEM / PSDB / SD / PSD",
    "26" : "PSB / PT / PSOL / PC do B",
    "27" : "PP / PDT / PMDB",
    "28" : "PSC / PPS / PRTB / PMN / PTC / PRP / PPL / PTB",
    "29" : "PR / PRB / PHS / PROS / PSDC / PEN / PV / PT do B",
    "30" : "PTB / PSC / PPS / PRTB / PMN / PTC / PRP / PPL",
    "31" : "PROS / DEM / PSL / PTN / PSC / PR / PRTB / PHS / PTC / PV / PRP / PSDB / PEN / PSD / SD / PT do B",
    "32" : "PMDB / PP / PT / PDT / PTB / PPS / PRB / PSDC / PPL / PC do B",
    "33" : "PR / PRB / PHS",
    "34" : "PT do B / PTN",
    "35" : "PROS / PV / PSDC / PEN",
    "36" : "PSOL / PT / PC do B",
    "37" : "PTB / PPS / PRTB / PMN / PTC / PPL",
    "38" : "PROS / DEM / PSDB / PR / PTN / PSC / PT do B / PTC / PRTB / PEN / PV / PHS / PSL / PSD / SD",
    "39" : "PSB / PSL / PPL",
    "40" : "PRTB / PEN",
    "41" : "DEM / PSDB / PMDB / SD / PTN / PROS / PRB / PSC / PTC / PV / PPS / PRP / PT do B / PSDC",
    "42" : "PT / PP / PSD / PDT / PR / PC do B / PTB / PMN",
    "43" : "DEM / PEN / PHS",
    "44" : "PTN / PRTB",
    "45" : "PMDB / PP / PT / PTB / PRB",
    "46" : "PROS / PSD / PSDB / PSC",
    "47" : "PSDC / PPL",
    "48" : "PR / PT do B / PSL / SD / PRP",
    "49" : "PPS / PDT",
    "50" : "PV / PTC",
    "51" : "PPS / PSDC / PTC / PV / PRP / PT do B",
    "52" : "PP / PDT / PT / PTB / PR / PSD",
    "53" : "DEM / PMDB / PSDB / PTN / SD / PROS / PRB / PSC",
    "54" : "PMN",
    "55" : "PP / PDT / PT / PTB / PR / PSD / PC do B",
    "56" : "PSTU / PCB / PSOL",
    "57" : "PRB / PP / PDT / PT / PTB / PSL / PRTB / PHS / PMN / PTC / PV / PEN / PPL / PSD / PC do B / PT do B / SD / PROS",
    "58" : "PMDB / PSC / DEM / PSDC / PRP / PSDB / PR / PTN / PPS",
    "59" : "DEM / PPS / PSDC / PTN",
    "60" : "PMDB / PSC / PR / PRP / PSDB",
    "61" : "PTC / PEN / PT do B / PRTB / PMN / PPL / PV",
    "62" : "PRB / PP / PDT / PT / PTB / PSL / PHS / PSD / PC do B / SD / PROS",
    "63" : "PEN / PRTB / PPL",
    "64" : "PRB / PT / PTB / PSL / PHS / PV / PSD / SD / PROS",
    "65" : "PMDB / PR / DEM / PRP / PSDB",
    "66" : "PTN / PPS / PSDC",
    "67" : "PT do B / PMN / PP",
    "68" : "PT / PMDB / PRB / PC do B / PRP / PPL / PV / PP / PTN / PT do B / PSC / PROS / PTC / PSL / PHS / PEN",
    "69" : "PSB / SD / PDT / PSD",
    "70" : "PTB / PR / DEM / PRTB / PMN",
    "71" : "PSDB / PPS / PSDC",
    "72" : "PSOL / PSTU / PCB",
    "73" : "PMDB / PT do B / PRP / PHS / PEN / PV / PTN / PPL / PSL / PTC",
    "74" : "PT / PRB / PC do B / PP / PSC / PROS",
    "75" : "PR / PTB / PRTB / PMN / DEM",
    "76" : "PDT / PT",
    "77" : "PMDB / PSDB / DEM / SD / PEN / PROS / PRP",
    "78" : "PSB / PSDC / PSL / PP / PRTB / PT do B / PPS / PR / PSC / PSD / PTC / PC do B / PV / PHS / PTN / PPL / PMN / PRB / PTB",
    "79" : "PCB / PSTU",
    "80" : "PR / PTB",
    "81" : "PT / PP",
    "82" : "PRTB / PMN",
    "83" : "PSB / PDT / SD",
    "84" : "PSC / PROS",
    "85" : "PRP / PV",
    "86" : "PEN / PSL",
    "87" : "PT do B / PHS",
    "88" : "PC do B / PPL / PTN",
    "89" : "PRB / PTC",
    "90" : "PSDB / PSDC",
    "91" : "PR / PV / PSC / PPL",
    "92" : "PMDB / PEN / DEM",
    "93" : "SD / PSDB",
    "94" : "PRP / PROS",
    "95" : "PTN / PSL / PT do B / PP / PTB",
    "96" : "PSB / PPS / PSD / PMN",
    "97" : "PRB / PTC / PHS / PRTB / PSDC / PC do B",
    "98" : "PR / PSC / PPL / PT do B / PTC / PMN / PSDC / PC do B",
    "99" : "PRP / PEN",
    "100" : "PRTB / PSB / PSL / PTN",
    "101" : "PRB / PP / PTB / PHS / PPS / PSD / PV",
    "102" : "PMDB / DEM / PSDB / SD / PROS",
    "103" : "PSB / PSC / PRP",
    "104" : "PMDB / DEM / SD / PC do B / PRTB / PTN / PPL",
    "105" : "PRB / PP / PDT / PTB / PSL / PR / PPS / PHS / PMN / PTC / PV / PSDB / PEN / PSD / PT do B / PROS",
    "106" : "PSDB / PP / PR / PSD / PTB / PDT / PPS / PROS / PRB",
    "107" : "PROS / PPS / PEN / PV",
    "108" : "PSL / PTC",
    "109" : "PTN / PRTB / PC do B / PPL / SD",
    "110" : "DEM / PMDB",
    "111" : "PSDB / PP / PR / PSD / PTB",
    "112" : "PDT / PMN",
    "113" : "PMDB / PSL / PEN / PSDC / PRP / PTN / PMN / PSC / PHS / PRTB / PR / PRB / DEM / PSD / PV / PT / PTB / PT do B",
    "114" : "PP / SD / PROS / PSDB / PC do B / PSB / PDT / PTC / PPS",
    "115" : "PSL / PSDC / PRP / PTN / PRTB",
    "116" : "SD / PP / PC do B / PPS / PSDB / PSB",
    "117" : "PDT / PTC / PROS",
    "118" : "PT / PSD",
    "119" : "PEN / PMN / PHS / PSC / PT do B",
    "120" : "PMDB / DEM / PTB / PV / PRB / PR",
    "121" : "PEN / PMN / PHS / PSD",
    "122" : "PP / PROS / SD / PPS",
    "123" : "PSB / PDT / PC do B / PSDB",
    "124" : "PMDB / DEM / PTB / PV / PT do B / PSC / PRTB / PR",
    "125" : "PRP / PSDC / PTN",
    "126" : "PDT / PP / DEM / PSDB / PSB / PPS / PV / PTB / PSDC / PSC / PRP / PSL / PRB",
    "127" : "PHS / PMN",
    "128" : "PSD / PTC / PTN / PEN / PRTB / SD",
    "129" : "PT / PMDB / PROS / PR / PC do B",
    "130" : "PDT / PP / DEM / PSDB / PSB / PPS / PTB / PSC / PSL / PRB",
    "131" : "PT / PMDB / PROS / PR",
    "132" : "PRP / PSDC / PV",
    "133" : "PTB / PSL / PPS",
    "134" : "PTC / PEN / PTN / PRTB / SD",
    "135" : "PRP / PSC / PSDC / PRB / PV",
    "136" : "PDT / DEM / PSDB",
    "137" : "PT / PMDB / PR / PC do B / PROS",
    "138" : "PP / PSB",
    "139" : "PSDB / DEM / PSD / SD / PPS / PMN",
    "140" : "PT do B / PHS / PRTB",
    "141" : "PT / PR / PDT / PROS / PTC / PC do B / PTB / PSDC",
    "142" : "PRP / PSL / PPL / PV",
    "143" : "PMDB / PSB / PRB / PTN / PEN / PSC",
    "144" : "PMDB / PSB / PT do B / PSC / PHS / PRB / PRTB / PTN / PEN",
    "145" : "PDT / PT / PSL / PR / PSDC / PV / PROS / PC do B / PTB / PTC / PPL / PRP",
    "146" : "PTB / PSL / PRP",
    "147" : "PSB / PT do B / PRTB / PHS / PSC / PEN / PRB",
    "148" : "PV / PC do B / PTC / PPL",
    "149" : "PDT / PSDC",
    "150" : "PT / PR / PROS",
    "151" : "PT / PMDB / PC do B / PROS / PRB",
    "152" : "PT do B / PRP / PHS / PEN",
    "153" : "PSDB / PP / DEM / PSD / PTB / PPS / PV / PDT / PR / PMN / PSC / PSL / PTC / SD",
    "154" : "PSB / PPL / PRTB",
    "155" : "PSTU / PSOL",
    "156" : "PSC / PTC / PSL",
    "157" : "PT / PROS / PMDB / PRB",
    "158" : "DEM / PSDB / PP / PSD / PPS",
    "159" : "PTB / SD",
    "160" : "PRP / PEN / PHS",
    "161" : "PDT / PV",
    "162" : "PTN / PSDC",
    "163" : "PPS / PV / PDT",
    "164" : "DEM / PSDB / PP / PR / PSD / SD",
    "165" : "PTB / PMN",
    "166" : "PMDB / PT / DEM / PR / PDT / PROS / PHS / PC do B / PSL / PPL / PTN",
    "167" : "PSDB / PSD / PSB / PP / SD / PRB / PSC / PTB / PPS / PEN / PMN / PTC / PSDC / PT do B / PRP",
    "168" : "PSDB / PSD / PSB / PP / PSC / PTB / PPS / PT do B / PTC",
    "169" : "PR / DEM / PHS / PROS / PC do B / PSL / PDT / PPL",
    "170" : "PMDB / PT",
    "171" : "PRB / SD",
    "172" : "PMN / PRP / PEN",
    "173" : "PMDB / PT / DEM / PC do B / PHS / PSL / PROS / PDT / PPL / PTN / PR",
    "174" : "PDT / PPL / PTN / PSL",
    "175" : "PRB / PSDC / PMN / PRP / SD / PEN",
    "176" : "PSDB / PSD / PTB / PP",
    "177" : "PR / PHS / PROS",
    "178" : "PTC / PT do B",
    "179" : "PSDB / PEN / PR / PTB / PSD / SD / PMN / PPS / PT do B / PTN / PRB / PSDC / PSC / PP",
    "180" : "PSB / PT / PDT / DEM / PRTB / PRP / PV / PSL / PC do B / PHS / PPL",
    "181" : "PMDB",
    "182" : "PSB / DEM / PRTB / PDT / PRP / PV / PT / PSL / PC do B / PHS / PPL",
    "183" : "PSB / DEM / PRTB / PDT / PRP",
    "184" : "PSL / PC do B / PHS / PPL / PV",
    "185" : "PT do B / SD / PPS / PTN / PMN / PSDC / PRB",
    "186" : "PSDB / PEN / PP / PR / PTB",
    "187" : "PSD / PSC",
    "188" : "PSDB / PROS / DEM / PSB / PSD / PTB / PP / PPS / PSC / PR / SD / PSL / PSDC / PMN / PHS / PEN / PT do B",
    "189" : "PT / PDT / PC do B / PRB / PTN",
    "190" : "PMDB / PV / PPL",
    "191" : "PSDC / PEN / PTB / PHS / PMN / PROS",
    "192" : "PV / PPL",
    "193" : "PSDB / DEM / PR / PSC / PT do B / PP / SD / PSD / PPS",
    "194" : "PT / PDT / PRB / PTN / PC do B",
    "195" : "PSDC / PEN",
    "196" : "PSC / PR / PT do B",
    "197" : "PT / PDT / PC do B / PRB",
    "198" : "PSDB / DEM / PSB / PROS / PHS",
    "199" : "PP / PMN",
    "200" : "PTB / PT / PSC / PDT / PRB / PT do B",
    "201" : "PSOL / PMN",
    "202" : "PMDB / PC do B / PSB / PTC / PRP / PV / PTN / PR / PSD / PPS / PSDB / SD / PPL / DEM / PHS / PSDC / PROS / PP / PEN / PRTB / PSL",
    "203" : "PRP / PSDC",
    "204" : "PSL / PHS / PPS",
    "205" : "PSB / PMDB / PC do B / PR / PSD / PSDB / PPL / DEM / PEN / PTC",
    "206" : "PP / PROS",
    "207" : "PTN / PRTB / PV / SD",
    "208" : "PSB / PMDB / PC do B / PV / PR / PSD / PPS / PSDB / SD / PPL / DEM / PROS / PP / PEN / PTC",
    "209" : "PSDC / PTN / PRP / PSL / PHS / PRTB",
    "210" : "PSOL / PCB",
    "211" : "PT / PP / PTB / PHS / PR / PROS / PRP / SD",
    "212" : "PMDB / PSDB / PSB / PRB / PDT / PSL / PTN / PPS / DEM / PSDC / PMN / PTC / PSD / PC do B / PT do B / PV / PEN",
    "213" : "PV / PSL / PMN / PEN",
    "214" : "PTC / PTN / PPS / DEM / PT do B / PSDC",
    "215" : "PSDB / PMDB / PC do B / PSD / PRB / PDT / PSB",
    "216" : "PMDB / PTN / PTC / PDT / PSB / PSD / PRB / DEM / PSDC / PT do B / PC do B / PPS / PSDB",
    "217" : "PR / PT do B / PROS",
    "218" : "PMDB / PP / PSC / PTB / PSL / PPS / PTN / DEM / PSDC / PRTB / PHS / PMN / PTC / PRP / PSDB / PEN / PSD / SD",
    "219" : "PT / PV / PSB / PC do B",
    "220" : "PROS / PR / PT do B",
    "221" : "PHS / PTN",
    "222" : "PRP / PRTB / PPL",
    "223" : "PR / PROS",
    "224" : "PSDC / PMN / PTC",
    "225" : "PMDB / PP / PSC / PSD / PTB",
    "226" : "PT / PSB / PC do B",
    "227" : "SD / PSL",
    "228" : "PSDB / PPS / DEM",
    "229" : "PMDB / PR / PSB / PROS / PDT / SD / PSC / PTB / PPS / PHS / PSDB / PSDC / PRB / PTN / PV / PMN / PRP",
    "230" : "PSD / PT / PC do B / PT do B / PP / PEN / PRTB / PTC",
    "231" : "PRTB / PPL",
    "232" : "PTB / PTN",
    "233" : "PSDC / PMN",
    "234" : "PSC / PTC",
    "235" : "PMDB / PR / PSB / PROS / PDT / SD / PSC / DEM / PV / PMN / PRP / PSDB / PSDC / PRB",
    "236" : "PTC / PRTB",
    "237" : "PHS / PPS / PTB / PTN",
    "238" : "PSD / PT / PC do B / PT do B / PP / PEN",
    "239" : "PV / PHS / PPS / PTN / PTB",
    "240" : "PT / PT do B / PC do B",
    "241" : "PMDB / PSB / PR / DEM / PDT / SD / PROS",
    "242" : "PSDB / PSC / PSDC / PMN / PRB / PRP",
    "243" : "PSD / PP / PEN / PRTB / PTC",
    "244" : "PDT / PSC / DEM / PV / PEN",
    "245" : "PP / PRB / PSDB / SD",
    "246" : "PT / PTC / PC do B / PROS / PPL / PTB / PR",
    "247" : "PMDB / PSD / PPS / PSB / PHS / PT do B / PSL / PSDC",
    "248" : "PTB / PC do B / PR / PPL / PROS / PTC",
    "249" : "PSB / PPS / PSD / PT do B / PHS / PSL / PSDC",
    "250" : "PDT / PSC / PV / PEN / DEM",
    "251" : "PP / PRB / SD / PSDB",
    "252" : "PSD / PHS / PT do B / PSDC / PSL",
    "253" : "PSC / PV / PEN",
    "254" : "PDT / DEM",
    "255" : "PSDB / SD / PRB",
    "256" : "PSB / PPS",
    "257" : "PC do B / PPL / PR / PTC / PROS",
    "258" : "PMDB / PDT / PSB / PTN / PTB / PC do B / PRTB / PSL / PRP",
    "259" : "PP / PR / PPS / PROS / PV / PTC",
    "260" : "PSDB / PSDC / PSD / PEN / PHS / PSC / PMN / PT do B / PRB / DEM",
    "261" : "PSDB / PSDC / PSD / PEN / SD / PHS / PSC / PMN / PT do B / PRB / DEM",
    "262" : "PMDB / PRTB / PC do B / PDT / PRP / PSB / PTB / PSL / PTN",
    "263" : "PP / PR / PPS / PTC / PV / PROS",
    "264" : "PRB / PMN / PT do B",
    "265" : "PSDC / PHS / PSC",
    "266" : "PC do B / PSB / PSL",
    "267" : "PMDB / PTN / PTB",
    "268" : "PSDB / DEM",
    "269" : "PDT / PRTB / PRP",
    "270" : "PEN / SD / PSD",
    "271" : "PT / PDT / PC do B / PV / PTC",
    "272" : "PP / PTB / DEM",
    "273" : "PT / PDT / PV / PTC / PC do B",
    "274" : "PSB / PMDB / PSDB / PR / PRB / PSD / SD / PROS / PPS / PSC / PMN / PSDC / PT do B / PRTB / PHS / PSL / PPL / PTN / PEN / PRP",
    "275" : "PSDB / PR / PRB / PSD / SD / PROS / PRP / PMDB / PSB / PTN",
    "276" : "PRTB / PHS / PPL / PMN / PEN / PSDC / PT do B / PSC / PSL / PPS",
    "277" : "PPL / PMN",
    "278" : "PP / PSL / PTN / PPS / PRTB / PHS / PTC / PSB / PSDB / PEN / PT do B / SD",
    "279" : "PSD / PRB / PMDB / PR / PTB / PSC / PSDC / PROS / PV / PC do B / PDT / DEM",
    "280" : "PR / PSC / PMN / PEN",
    "281" : "PSL / PSDC / PPL / PT do B",
    "282" : "PMDB / SD / PSD / PSB / PSDB / PROS / PTN",
    "283" : "PHS / PRTB / PPS",
    "284" : "PV / PDT / PTC",
    "285" : "PT / PC do B",
    "286" : "PSD / DEM / PMDB / PRB",
    "287" : "PDT / PROS / PTB / PC do B / PSDC / PV",
    "288" : "PSDB / PEN",
    "289" : "PSB / PPS / PTC / PHS / PSL / PT do B / PRTB / PTN / SD",
    "290" : "PT do B / PSL / PTN",
    "291" : "PP / PPS / PRTB / PHS / PSDB / PEN / SD / PTC / PSB",
    "292" : "PSD / PC do B / PV / PMDB / PR / PTB / PSC / PSDC / PROS / PRB / PDT / DEM",
    "293" : "PT / PC do B / PR",
    "294" : "PHS / PRP",
    "295" : "PMDB / PROS / PSD / PP / PDT",
    "296" : "PSDB / DEM / PEN / PMN / PT do B / PTC / PTN / SD / PPS / PRB / PSB / PSC / PSDC / PSL",
    "297" : "PMDB / PROS / PP / PSD",
    "298" : "PSL / PTN / PMN / PTC / PT do B",
    "299" : "PSDB / DEM / PPS",
    "300" : "DEM / PSDB / PP / PT do B / PSC / PTC / PSL / PTB / SD / PV / PPS / PHS / PMN / PR / PEN",
    "301" : "PT / PSD / PC do B / PRTB / PDT / PRP / PROS / PSDC / PMDB / PSB / PRB",
    "302" : "PP / PMDB / PSD",
    "303" : "PSDB / DEM / PPS / PRB",
    "304" : "PRB / PDT / PRP / PROS / PC do B / PSDC",
    "305" : "PPS / PMN / PHS / PV / PEN",
    "306" : "PP / PTB / PSL / PSC / PR / DEM / PT do B / PTC / SD / PSDB",
    "307" : "PT / PMDB / PSB / PSD",
    "308" : "PP / PTB / PSL / PSC / PR / PPS / DEM / PHS / PTC / PV / PSDB / PEN / PT do B / SD",
    "309" : "PT / PDT / PSB / PMDB / PC do B / PRP / PROS / PSD / PRB / PSDC"
}
  },

  run : function (where, cb) {
    Candidato.where(where).count(function (e, c) {
      var data = {},
          values = _.values(where);
      if (values.length == 2) {
        data[values[0]] = {};
        data[values[0]][values[1]] = c;
      } else {
        data[_.values(where)[0]] = c;
      }

      cb(null, data);
    });
  },

  after : function (results) {
    var data = {};
    _.each(results, function (v,k) {
      _.merge(data, v);
    });
    return data;
  }
}

/* GET home page. */
router.get('/', function(req, res) {
    res.render('index', {
      subtitle:
      'Uma série de visualizações extraídas da base de candidatos'+
      ' disponibilizado pelo TSE, no '+
      '<a href="http://divulgacand2014.tse.jus.br">site</a>. O código-fonte'+
      ' desse site e uma breve história de como e porque criamos, você'+
      'pode encontrar no <a href="https://github.com/lucaspirola/infografico-candidatos-eleicoes-2014">github</a>.',
      title: 'Extrato dos candidatos da eleição de 2014'
    });
});

router.get('/data', function(req, res){
  var param_filter = req.query.filter,
      tasks        = [];

  if (param_filter.indexOf(',')>0) {
    var params = param_filter.split(',');
    var main_param = params[0];
    var second_param = params[1];

    _.each(filter.options[main_param], function (v,k) {
      var data = {};
      data[main_param] = v;

      _.each(filter.options[second_param], function (v,k) {
        tasks.push(function (cb) {
          data[second_param] = v;
          filter.run(data, cb);
        });
      });
    });
  } else {
    _.each(filter.options[param_filter], function (v,k) {
      tasks.push(function (cb) {
        var data = {};
        data[param_filter] = v;
        filter.run(data, cb);
      });
    });
  }

  async.series(tasks, function(err,results){
    res.json(filter.after(results));
  });

});

module.exports = router;
